name: inari_log
description: inari log

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  collection: ^1.15.0
  intl: ^0.17.0

  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4


  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0

  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.0.5

  flutter_image_compress: ^1.0.0-nullsafety

  geocoding: ^2.0.0

  font_awesome_flutter: ^9.1.0

  file_picker: ^3.0.4
  image_picker_web: ^2.0.3
  fluro: ^2.0.3
  cached_network_image: ^3.1.0

  image_compression: ^1.0.3

dev_dependencies:
  build_runner: ^2.0.5
  freezed: ^0.14.2

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons fonts is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the fonts family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the fonts. For
  # example:
  fonts:
    - family: NotoSansJP-Regular
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf

    - family: NotoSansJP-Bold
      fonts:
        - asset: fonts/NotoSansJP-Bold.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

